### ISSUE TITLE
Error when evaluating SSR module

### ISSUE THREAD

**Issue by serban-mihai** [phi-ag/solid-pages#90] opened 2024-12-22 11:16 UTC
Awesome approach you set up for making Cloudflare bindings available for SolidStart over Cloudflare Pages, but I'm encountering a problem when trying to run it on the local environment with `vinxi dev`:
```
[vite] Error when evaluating SSR module /node_modules/@solidjs/router/dist/index.js:
|- Error: Client-only API called on the server side. Run client-only code in onMount, or conditionally run client-only component with <Show>.
    at Module.notSup (file:///solid-pages/node_modules/solid-js/web/dist/server.js:1136:9)
    at eval (/solid-pages/node_modules/@solidjs/router/dist/index.js:1625:49)
    at async instantiateModule (file:///solid-pages/node_modules/@solidjs/start/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52972:5)

12:11:15 PM [vite] Error when evaluating SSR module /src/middleware.ts:
|- Error: Client-only API called on the server side. Run client-only code in onMount, or conditionally run client-only component with <Show>.
    at Module.notSup (file:///solid-pages/node_modules/solid-js/web/dist/server.js:1136:9)
    at eval (/solid-pages/node_modules/@solidjs/router/dist/index.js:1625:49)
    at async instantiateModule (file:///solid-pages/node_modules/@solidjs/start/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52972:5)

12:11:15 PM [vite] Error when evaluating SSR module $vinxi/handler/ssr:
|- Error: Client-only API called on the server side. Run client-only code in onMount, or conditionally run client-only component with <Show>.
    at Module.notSup (file:///solid-pages/node_modules/solid-js/web/dist/server.js:1136:9)
    at eval (/solid-pages/node_modules/@solidjs/router/dist/index.js:1625:49)
    at async instantiateModule (file:///solid-pages/node_modules/@solidjs/start/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52972:5)
```

On a production build it works perfectly with the `start` script. Still, I'd like to know if you've been able to set it up to be somehow able to use `wrangler dev` to have access to bindings, and hot reload to be able to develop without building after each style edit.

**Comment by peterhirn** [comment] 2024-12-22 11:32
Hey. `vinxi dev` did work for me on this very minimal demo app, but the error you are seeing seems very familiar.

Are you running this app or something custom?

I'm currently not at my machine and will update this issue with more infos later.

**Comment by peterhirn** [comment] 2024-12-22 11:41
Issue was probably introduced here: https://github.com/phi-ag/solid-pages/commit/f11f0d7f7a0ebe217425d8e270d3de6fff85b415

If you downgrade vinxi and vite manually it might work again?

**Comment by serban-mihai** [comment] 2024-12-22 12:00
> Are you running this app or something custom?

Hey, thanks for the quick reply.
I've just cloned the repo and tried to run it, no edits have been done, only that I use NPM instead of PNPM

> If you downgrade vinxi and vite manually it might work again?

That worked!
```
"vinxi": "0.4.3",
"vite": "5.4.11",
```
I don't understand what breaking changes were introduced in these packages to make it complain the way it does.
Might it be because I'm using npm for any reason? I use the latest versions of both npm and node,

Thank you so much!

**Comment by peterhirn** [comment] 2024-12-22 12:20
I'm sure using npm is not the problem. Either vinxi broke something or I'm doing it wrong 😅

I'll revert the update and investigate this further later today.

**Comment by peterhirn** [comment] 2024-12-22 19:34
I just checked, the problem is actually `npm` 😬

`@solidjs/start` currently depends on `vinxi` v0.4.3

Using `pnpm` this problem is circumvented with this `package.json` snippet

```json
  "pnpm": {
    "overrides": {
      "vinxi": "$vinxi"
    }
  }
```

So your options are
- switch to `pnpm`
- stay on  `vinxi` v0.4.3 (and `vite` v5) until `@solidjs/start` is updated

I wasn't able to find any issues/PRs/discussion on this topic for [SolidStart](https://github.com/solidjs/solid-start) but [this](https://github.com/solidjs/solid-start/commit/426644e81c6e31da85c1a86d00324f8271a44b5f) commit by Ryan from last week suggests there are issues with `vite` v6

> temporarily lock examples to vite 5 until we can solve upstream issues

I'm closing this issue for now but I'm happy to discuss this further.

**Closed by peterhirn** 2024-12-22 19:34 UTC
